name: "Godot Android Build"
on: 
  push:
    branches:
      - master

jobs:
  export_android:
    runs-on: ubuntu-latest
    name: Export Android APK
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
          godot_template_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
        env:
          RELATIVE_PATH_TO_EXPORT_PRESETS: ./export_presets.cfg